logging: 
  config: classpath:logback-dev.xml
spring:
  data:
    mongodb:
      uri: mongodb://root:root1@120.79.145.235:27017/ss_test
starrysea:
  split:
    input: D:/chatHistory/raw
    output: D:/chatHistory/result